<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-28T16:25:34 IST" name="Default suite" finished-at="2023-03-28T16:25:43 IST" duration-ms="9143">
    <groups>
    </groups>
    <test started-at="2023-03-28T16:25:34 IST" name="Default test" finished-at="2023-03-28T16:25:43 IST" duration-ms="9143">
      <class name="HomeTask_RestFunctional.HomeTaskRestFunctionalTest1">
        <test-method signature="SendGetRequestToFetchResource()[pri:0, instance:HomeTask_RestFunctional.HomeTaskRestFunctionalTest1@71def8f8]" started-at="2023-03-28T16:25:34 IST" name="SendGetRequestToFetchResource" finished-at="2023-03-28T16:25:40 IST" duration-ms="5570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendGetRequestToFetchResource -->
        <test-method signature="createResource()[pri:0, instance:HomeTask_RestFunctional.HomeTaskRestFunctionalTest1@71def8f8]" started-at="2023-03-28T16:25:40 IST" name="createResource" finished-at="2023-03-28T16:25:41 IST" duration-ms="1018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createResource -->
        <test-method signature="getResource()[pri:1, instance:HomeTask_RestFunctional.HomeTaskRestFunctionalTest1@71def8f8]" started-at="2023-03-28T16:25:41 IST" name="getResource" finished-at="2023-03-28T16:25:42 IST" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResource -->
        <test-method signature="updateResource()[pri:2, instance:HomeTask_RestFunctional.HomeTaskRestFunctionalTest1@71def8f8]" started-at="2023-03-28T16:25:42 IST" name="updateResource" finished-at="2023-03-28T16:25:42 IST" duration-ms="714" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateResource -->
        <test-method signature="deleteResource()[pri:3, instance:HomeTask_RestFunctional.HomeTaskRestFunctionalTest1@71def8f8]" started-at="2023-03-28T16:25:42 IST" name="deleteResource" finished-at="2023-03-28T16:25:43 IST" duration-ms="1186" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Response code is not matching expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Response code is not matching expected [404] but found [200]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at HomeTask_RestFunctional.HomeTaskRestFunctionalTest1.deleteResource(HomeTaskRestFunctionalTest1.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteResource -->
      </class> <!-- HomeTask_RestFunctional.HomeTaskRestFunctionalTest1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
